### ISSUE TITLE
Question: Should annotations persist after issues are resolved?

### ISSUE THREAD

**Issue by jmealo** [a-b-r-o-w-n/eslint-action#12]
Thanks for your hard work! This was the only GitHub action that works for me in a mono-repo where `working-directory` is not the repository root. :)

When all lint issues are solved, the annotations for the failed lines persist, even when I re-run tests.

I'm not sure if this is an issue with my workflow file or intended behavior:

```yaml
      - name: Save Code Linting Report JSON
        run: npm run lint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.0.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "backend/eslint_report.json"
      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report.json
          path: backend/eslint_report.json
```
