### ISSUE TITLE
Error loading modules

### ISSUE THREAD

**Issue by geoperez** [a-b-r-o-w-n/eslint-action#7]
Hi,

I'm trying to use this action but I'm getting an error loading a module. My React Typescript application is not located in the root. So I use the following argument to point in the right path:

```
 files: src/Unosquare.AssetCore.Server/client-app/src/**/*
```

It seems like eslint is finding my config file but not the related modules declared:

```
##[error]Failed to load plugin 'react' declared in 'src/Unosquare.AssetCore.Server/client-app/.eslintrc.js': Cannot find module 'eslint-plugin-react'
```

The node_modules folder is restored before to use this GH Action.

Thanks!

**Comment by a-b-r-o-w-n** [comment]
Thanks for the report. I suspect there is more work to be done to handle monorepo setups. I’ll see what I can do.

**Comment by a-b-r-o-w-n** [comment]
@geoperez Can you share the action workflow you are using?

**Comment by geoperez** [comment]
Sure:

```
name: Lint PR

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1   
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - run: npm ci
        working-directory: src/Unosquare.AssetCore.Server/client-app
      - name: Lint
        uses: a-b-r-o-w-n/eslint-action@v1
        with:
          repo-token:  ${{ secrets.GITHUB_TOKEN }}
          files: 'src/Unosquare.AssetCore.Server/client-app/src/**/*'
```
